%YAML:1.0
---
data_type: picture
video_path: /home/tianru/slam/slam-learning/data/video/demo2.mp4
video_w: 1400
video_h: 800
video_rate: 30
picture_path: /home/tianru/slam/KITTI/dataset/sequences/01/image_0/
picture_index_min: 0
picture_index_max: 1000
picture_rate: 100

showrods: 1
trackrate: 0.4
