%YAML:1.0
---
data_type: video
video_path: /home/tianru/slam/slam-learning/data/video/demo2.mp4
video_w: 900
video_h: 500
video_rate: 100
picture_path: /home/tianru/slam/KITTI/dataset/sequences/01/image_0/
picture_rate: 60
